
# Move Base Parameters
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
recovery_behaviors:  [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: rotate_recovery, type: rotate_recovery/RotateRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
controller_frequency: 8
planner_patience: 5
controller_patience: 15

# conservative_reset_dist: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
# shutdown_costmaps: false
# oscillation_timeout: 0.0
# oscillation_distance: 0.5
# planner_frequency: 0.0
# max_planning_retries: -1

# Global Planner Parameters
BaseGlobalPlanner:
  allow_unknown: false
  use_dijkstra: false #Use A* instead
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false

# Local Planner Parameters
TrajectoryPlannerROS:
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  max_vel_x: 0.235
  min_vel_x: -0.235
  max_vel_theta: 0.25
  min_vel_theta: -0.25
  min_in_place_vel_theta: 0.35

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.5

  sim_time: 4.0
  sim_period: 0.1
  sim_granularity: 0.1
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 8

  meter_scoring: true
  path_distance_bias: 0.4
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  dwa: true
  publish_cost_grid_pc: true
  prune_plan: false
  holonomic_robot: false