# Global Costmap Parametes
global_costmap:
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [ [0.35, 0.35], [-0.35, 0.35], [-0.35, -0.35], [0.35, -0.35] ]
  inflation_radius: 0.02

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  transform_tolerance: 0.5
  static_map: true
  # publish_frequency: 5.0

  # rolling_window: true
  # always_send_full_costmap: false

  # footprint_padding: 0.02
