# Local Costmap Parameters
local_costmap:
  obstacle_range: 8.0
  raytrace_range: 8.0
  footprint: [ [0.35, 0.35], [-0.35, 0.35], [-0.35, -0.30], [0.35, -0.30] ]
  inflation_radius: 0.02

  map_type: costmap
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true #origin of the local cost_map / false = bottom left coner true: center
  width: 10.0
  height: 10.0
  resolution: 0.05